# DEV PROFILE
spring.datasource.url=jdbc:postgresql://localhost:5432/vsu_research_app
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=false
logging.level.com.vsu.researchapp=DEBUG
logging.level.org.springframework.security=DEBUG

# Dev swagger open
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Dev mail - just log emails don't send
spring.mail.host=localhost
spring.mail.port=1025

# Dev Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379