# PROD PROFILE
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_DB}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
logging.level.com.vsu.researchapp=INFO
logging.level.org.springframework.security=WARN

# Prod swagger locked down
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

# Prod mail
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

# Prod Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# Prod session
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true